# Tên ứng dụng
spring.application.name=foodweb

# Cấu hình kết nối MySQL trên Railway
spring.datasource.url=jdbc:mysql://metro.proxy.rlwy.net:52912/railway?useSSL=false&serverTimezone=UTC&allowPublicKeyRetrieval=true
spring.datasource.username=root
spring.datasource.password=qubDHJGiEVgliTXMuYkSIVcTsJFBzGpt
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver

# Hiển thị câu lệnh SQL trong logs
spring.jpa.show-sql=true

# Hibernate - Tạo bảng nếu chưa có, không làm mất dữ liệu
spring.jpa.hibernate.ddl-auto=update
spring.jpa.database-platform=org.hibernate.dialect.MySQL8Dialect

# Cấu hình JWT (Bảo mật)
spring.application.security.jwt.secretKey=404E635266556A586E3272357538782F413F4428472B4B6250645367566B5970
spring.application.security.jwt.expiration=86400000 
spring.application.security.jwt.refreshTokenExpiration=604800000 

# Cấu hình đường dẫn lưu trữ ảnh
spring.mvc.static-path-pattern=/images/**
spring.resources.static-locations=file:./uploaded-images/
